plugins:
  - inline
  - convert
  - duplicates
  - edit
  - export
  - fetchart
  - albumtypes
  - permissions
  - bareasc
  - unimported
per_disc_numbering: no

directory: ~/music
library: ~/music/db
convert:
  auto: yes
  dest: ~/music/converted
  embed: yes
  copy_album_art: yes
  never_convert_lossy_files: yes
  format: opus
  formats:
    mp3: ffmpeg -i $source -y -vn -aq 10 -ab 320k -ac 2 -ar 48000 $dest
    ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 10 $dest
    opus: ffmpeg -i $source -y -vn -acodec libopus -ab 256k -vbr on $dest
albumtypes:
  types:
    - ep: 'EP'
    - single: 'Single'
    - live: 'Live'
    - remix: 'Remix'
  bracket: '[]'
paths:
  default: albums/$albumartist/$year - $album%if{$atypes, }$atypes/%if{$multidisc,$disc-}$track $title
  singleton: singletons/$artist - $title
  comp: compilations/$year - $album%aunique{}%if{$atypes, }$atypes/%if{$multidisc,$disc-}$track $title
  albumtype:soundtrack: soundtracks/$year - $album%aunique{}%if{$atypes, }$atypes/%if{$multidisc,$disc-}$track $title
  albumtype:stream: streams/$albumartist/$year - $album%aunique{}%if{$atypes, }$atypes/%if{$multidisc,$disc-}$track $title
item_fields:
  multidisc: 1 if disctotal > 1 else 0
import:
  autotag: no
  write: no
  incremental: yes
  log: ~/music/beet.log
fetchart:
  auto: yes
permissions:
  file: 640
  dir: 750
unimported:
  ignore_extensions: nsp ndignore log
  ignore_subdirectories: unsorted
