plugins: inline convert duplicates edit export fetchart thumbnails albumtypes musicbrainz
threaded: yes
alt_filename: albumart
original-date: no
per_disc_numbering: no

directory: ~/music/library
library: ~/music/library/db
convert:
  auto: yes
  embed: yes
  copy_album_art: yes
  opts: -ab 320k -ac 2 -ar 48000
  never_convert_lossy_files: yes
  extension: mp3
albumtypes:
  types:
    - ep: 'EP'
    - op: 'OP'
    - single: 'Single'
    - live: 'Live'
    - remix: 'Remix'
  bracket: '[]'
paths:
  default: artists/$albumartist/$album%aunique{} [$year]$atypes/$track $title
  singleton: singles/$artist - $title
  comp: compilations/$album%aunique{} [$year]$atypes/$track $title
  albumtype:soundtrack: soundtracks/$album [$year]$atypes/$track $title
import:
  write: no
  copy: yes
  move: no
  resume: ask
  incremental: yes
  quiet_fallback: skip
  log: ~/music/library/beet.log
musicbrainz:
  extra_tags: [barcode, catalognum, country, year]
  genres: yes
  external_ids:
    bandcamp: yes
    discogs: yes
    spotify: yes
    tidal: yes
